const Pokemon = (name, id, hasShiny) => ({
	name,
	pokeapiUrl: `https://pokeapi.co/api/v2/pokemon-species/${id}/`,
	sprites: {
		normal: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`,
		shiny:
			hasShiny &&
			`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${id}.png`
	},
	hasShiny,
	id
})

export default [
	new Pokemon('bulbasaur', 1, true),
	new Pokemon('ivysaur', 2, true),
	new Pokemon('venusaur', 3, true),
	new Pokemon('charmander', 4, true),
	new Pokemon('charmeleon', 5, true),
	new Pokemon('charizard', 6, true),
	new Pokemon('squirtle', 7, true),
	new Pokemon('wartortle', 8, true),
	new Pokemon('blastoise', 9, true),
	new Pokemon('caterpie', 10, true),
	new Pokemon('metapod', 11, true),
	new Pokemon('butterfree', 12, true),
	new Pokemon('weedle', 13, false),
	new Pokemon('kakuna', 14, false),
	new Pokemon('beedrill', 15, false),
	new Pokemon('pidgey', 16, false),
	new Pokemon('pidgeotto', 17, false),
	new Pokemon('pidgeot', 18, false),
	new Pokemon('rattata', 19, false),
	new Pokemon('raticate', 20, false),
	new Pokemon('spearow', 21, false),
	new Pokemon('fearow', 22, false),
	new Pokemon('ekans', 23, false),
	new Pokemon('arbok', 24, false),
	new Pokemon('pikachu', 25, true),
	new Pokemon('raichu', 26, true),
	new Pokemon('sandshrew', 27, true),
	new Pokemon('sandslash', 28, true),
	new Pokemon('nidoran♀', 29, true),
	new Pokemon('nidorina', 30, true),
	new Pokemon('nidoqueen', 31, true),
	new Pokemon('nidoran♂', 32, false),
	new Pokemon('nidorino', 33, false),
	new Pokemon('nidoking', 34, false),
	new Pokemon('clefairy', 35, false),
	new Pokemon('clefable', 36, false),
	new Pokemon('vulpix', 37, false),
	new Pokemon('ninetales', 38, false),
	new Pokemon('jigglypuff', 39, false),
	new Pokemon('wigglytuff', 40, false),
	new Pokemon('zubat', 41, false),
	new Pokemon('golbat', 42, false),
	new Pokemon('oddish', 43, false),
	new Pokemon('gloom', 44, false),
	new Pokemon('vileplume', 45, false),
	new Pokemon('paras', 46, false),
	new Pokemon('parasect', 47, false),
	new Pokemon('venonat', 48, false),
	new Pokemon('venomoth', 49, false),
	new Pokemon('diglett', 50, false),
	new Pokemon('dugtrio', 51, false),
	new Pokemon('meowth', 52, false),
	new Pokemon('persian', 53, false),
	new Pokemon('psyduck', 54, true),
	new Pokemon('golduck', 55, true),
	new Pokemon('mankey', 56, false),
	new Pokemon('primeape', 57, false),
	new Pokemon('growlithe', 58, true),
	new Pokemon('arcanine', 59, true),
	new Pokemon('poliwag', 60, false),
	new Pokemon('poliwhirl', 61, false),
	new Pokemon('poliwrath', 62, false),
	new Pokemon('abra', 63, false),
	new Pokemon('kadabra', 64, false),
	new Pokemon('alakazam', 65, false),
	new Pokemon('machop', 66, false),
	new Pokemon('machoke', 67, false),
	new Pokemon('machamp', 68, false),
	new Pokemon('bellsprout', 69, false),
	new Pokemon('weepinbell', 70, false),
	new Pokemon('victreebel', 71, false),
	new Pokemon('tentacool', 72, false),
	new Pokemon('tentacruel', 73, false),
	new Pokemon('geodude', 74, true),
	new Pokemon('graveler', 75, true),
	new Pokemon('golem', 76, true),
	new Pokemon('ponyta', 77, true),
	new Pokemon('rapidash', 78, true),
	new Pokemon('slowpoke', 79, false),
	new Pokemon('slowbro', 80, false),
	new Pokemon('magnemite', 81, true),
	new Pokemon('magneton', 82, true),
	new Pokemon('farfetchd', 83, false),
	new Pokemon('doduo', 84, false),
	new Pokemon('dodrio', 85, false),
	new Pokemon('seel', 86, false),
	new Pokemon('dewgong', 87, false),
	new Pokemon('grimer', 88, true),
	new Pokemon('muk', 89, true),
	new Pokemon('shellder', 90, true),
	new Pokemon('cloyster', 91, true),
	new Pokemon('gastly', 92, true),
	new Pokemon('haunter', 93, true),
	new Pokemon('gengar', 94, true),
	new Pokemon('onix', 95, false),
	new Pokemon('drowzee', 96, true),
	new Pokemon('hypno', 97, true),
	new Pokemon('krabby', 98, true),
	new Pokemon('kingler', 99, true),
	new Pokemon('voltorb', 100, false),
	new Pokemon('electrode', 101, false),
	new Pokemon('exeggcute', 102, false),
	new Pokemon('exeggutor', 103, false),
	new Pokemon('cubone', 104, true),
	new Pokemon('marowak', 105, true),
	new Pokemon('hitmonlee', 106, false),
	new Pokemon('hitmonchan', 107, false),
	new Pokemon('lickitung', 108, false),
	new Pokemon('koffing', 109, false),
	new Pokemon('weezing', 110, false),
	new Pokemon('rhyhorn', 111, false),
	new Pokemon('rhydon', 112, false),
	new Pokemon('chansey', 113, false),
	new Pokemon('tangela', 114, false),
	new Pokemon('kangaskhan', 115, false),
	new Pokemon('horsea', 116, false),
	new Pokemon('seadra', 117, false),
	new Pokemon('goldeen', 118, false),
	new Pokemon('seaking', 119, false),
	new Pokemon('staryu', 120, false),
	new Pokemon('starmie', 121, false),
	new Pokemon('mr mime', 122, false),
	new Pokemon('scyther', 123, false),
	new Pokemon('jynx', 124, false),
	new Pokemon('electabuzz', 125, true),
	new Pokemon('magmar', 126, true),
	new Pokemon('pinsir', 127, true),
	new Pokemon('tauros', 128, false),
	new Pokemon('magikarp', 129, true),
	new Pokemon('gyarados', 130, true),
	new Pokemon('lapras', 131, false),
	new Pokemon('ditto', 132, false),
	new Pokemon('eevee', 133, true),
	new Pokemon('vaporeon', 134, true),
	new Pokemon('jolteon', 135, true),
	new Pokemon('flareon', 136, true),
	new Pokemon('porygon', 137, false),
	new Pokemon('omanyte', 138, true),
	new Pokemon('omastar', 139, true),
	new Pokemon('kabuto', 140, true),
	new Pokemon('kabutops', 141, true),
	new Pokemon('aerodactyl', 142, true),
	new Pokemon('snorlax', 143, true),
	new Pokemon('articuno', 144, true),
	new Pokemon('zapdos', 145, true),
	new Pokemon('moltres', 146, true),
	new Pokemon('dratini', 147, true),
	new Pokemon('dragonair', 148, true),
	new Pokemon('dragonite', 149, true),
	new Pokemon('mewtwo', 150, false),
	new Pokemon('mew', 151, false)
]
